# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'NAS-T' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NAS-T
  pod 'Alamofire', '~> 4.3'
  pod 'SwiftyJSON'
end
